<?php

namespace SistemaIntegradoIgrejas\Repositories;

use Prettus\Repository\Eloquent\BaseRepository;
use SistemaIntegradoIgrejas\Entities\User;
use SistemaIntegradoIgrejas\Presenters\UserPresenter;

class UserRepositoryEloquent extends BaseRepository implements UserRepository
{
    public function model()
    {
        return User::class;
    }

    public function presenter()
    {
        #return parent::presenter(); // TODO: Change the autogenerated stub
        return UserPresenter::class;
    }

}